### ISSUE TITLE
Total PC-Lint Warnings: 0

### ISSUE THREAD

**Issue by jonrietveld** [greghoeppner/LintIt#6]
Trying to run lint gives an output of 0 warnings while running lint in legacy mode seems to output the correct lint output. It seems like PC Lint is not being called, however the correct path to pc lint is set in the lintit settings file, and does not contain any spaces. The path to my project does contain spaces, however I tried removing spaces in the path but that did not seem to make a difference. I am running on Windows. Could this have something to do with the \ or / characters and how they are parsed? I also have my lint file correctly labeled in the settings.json file. Is there a way to see the debug output from this extension? The only output I am getting is "Total PC-Lint Warnings: 0"

**Comment by greghoeppner** [comment]
The Legacy move required that you had a batch file run pc-lint and output a file called lint.log. is there a reason you wanted to use legacy mode vs the new configuration options

**Comment by jonrietveld** [comment]
I would like to use the new configuration, but it seems to output 0 warnings in normal mode. I have only been able to get legacy mode to work. I did notice when creating the legacy mode file that PC Lint is particular about spacing. Could that have something to do with it?

**Comment by greghoeppner** [comment]
It is possible. If you are comfortable, you could attach your lint.log file or paste it in as a comment and I could debug it. I am away from my PC until tomorrow. I can send you my configuration and we can try to get yours configured.

**Comment by jonrietveld** [comment]
Where is lint.log located? I am not seeing that output in either the lint folder or the project folder

**Comment by greghoeppner** [comment]
Ok. I think you might not be setup correctly for legacy mode. Can you copy in your current configuration from the settings.json?

**Comment by jonrietveld** [comment]
Legacy mode does work correctly, but non-legacy mode does not work. Here is my config for non-legacy mode:
    "lintit.pcLintLocation": "C:\\PC_Lint\\pclp64.exe",
    "lintit.configurations": [
        {
            "includeFolders": [],
            "libraryIncludeFolders": [],
            "lintFiles": ["${workspaceFolder}\\co-iar-hcs12.lnt"],
            "sourceFolders": []
        }
    ],
    Does non-legacy mode output a log file as well?

**Comment by greghoeppner** [comment]
It doesn't right now but I could update to get a log file printed out.  I do output some information to the debug console.  You can toggle the developer tools to see the console.  I think I see the issue.  You need to specify the sourceFolders (where the c/cpp files are located).  If you are scanning the whole workspace, you could just change the line "sourceFolders": [] to "sourceFolders": ["${workspaceFolder}"].  My config looks like this:
```
{
    "lintit.pcLintLocation": "C:\\PCLintPlus\\pclp32.exe",
    "lintit.configurations": [
        {
            "includeFolders": [
                "${workspaceFolder}/lint",
                "${workspaceFolder}/src",
                "${workspaceFolder}/drivers",
                "${workspaceFolder}/drivers/protobuf",
            ],
            "libraryIncludeFolders": [],
            "lintFiles": ["${workspaceFolder}/lint/application.lnt"],
            "sourceFolders": ["${workspaceFolder}/src"],
            "extensions": [".c",".cpp"]
        }
    ],
}
```

**Comment by jonrietveld** [comment]
That worked! My config is now below:
`    "lintit.pcLintLocation": "C:\\PC_Lint\\pclp64.exe",
    "lintit.configurations": [
        {
            "includeFolders": ["${workspaceFolder}"],
            "libraryIncludeFolders": [],
            "lintFiles": ["${workspaceFolder}/co-iar-hcs12.lnt"],
            "sourceFolders": ["${workspaceFolder}"],
            "extensions": [".c"]
        }
    ],`
    
I noticed that when I run lintit from the command palette, even with aggressive mode disabled that all files in my project are scanned. Is there a way to make it only scan the open file? Also, do wild cards work like vs code for selecting all sub folders to be included for example "includeFolders": ["${workspaceFolder}/**"]

**Comment by greghoeppner** [comment]
Glad that worked! I have the command palette command do all the files and if you open a file, it scans it separately and puts the lint problems in the PROBLEMS tab.  I could add a setting that would only lint the open files if that is something that you want.  I like the idea of the wildcards for the include folders.  I'll try to get that one implemented.

**Comment by jonrietveld** [comment]
I was wondering about scanning just one file because I noticed that supplemental info for each of the warnings is not put in the PROBELMS tab, so I was using the clickable links from the lintit output tab to get that info. Is there a setting that needs to be enabled in LintIt or a setting VS code to add supplemental information to the PROBLEMS tab, maybe as INFO messages?

**Comment by greghoeppner** [comment]
Oh,  I will look into those not showing up.  I have them directly mapped right now (error is error, info is info) but I can make a supplemental an info as well.

**Comment by jonrietveld** [comment]
That would be great! Because supplemental info can be disabled in the lint config, they could still be removed from the output window if needed. I like how each of the clickable links are under the their own collapsible section in the PROBLEMS tab. It makes jumping between issue very quick.

**Comment by greghoeppner** [comment]
@jonrietveld I updated the plugin to version 0.3.4 which now detects the supplemental messages.  Also added issue #7 for the wildcard feature request you had.

**Comment by jonrietveld** [comment]
Thanks for adding those. This is a really great extension!
