### ISSUE TITLE
Not running on linux OS

### ISSUE THREAD

**Issue by GitoPhill** [greghoeppner/LintIt#8]
First off: I appreciate your work on this extension. Thank you very much.

I am working in a remote linux dev environment and cannot get the plugin working with the pclp64 linux version. The plugin is installed inside my Ubuntu WSL. PCLint plus is also installed within the WSL.

Everything seems to be setup according to the provided description (path to pclp64_linux within the WSL and all the other folders). When I invoke lintit, a popup error message appears stating something like this:

"The command LintIt: Run triggered an error (Systemerror (ENOENT: no such file or directory, scandir "\<path as provided as sourceFolders>".

NOTE: The backslash in scandir output is always there. No matter what I do about the sourceFolders configuration.

I tried to provide the sourceFolders configuration in multiple different ways:
- "<absolute Path>"
- "${workspaceFolder}/<src>"
- "${workspaceFolder}\\<src>"

Nothing worked so far. 

Is it a matter of unix/windows path normalization or is the plugin only designed for windows? I have to admit, that I'm not too familiar with the VS Code extension architecture.

If this plugin is only designed for VS Code with Windows, it would be nice to explicitly state this as a prerequisite. 

In case you need any testing support, in order to resolve this issue, please let me know.

**Comment by greghoeppner** [comment]
I had originally written this for use with Windows but I would be happy to try to get it working in Linux as well.  I will attempt to get things setup later today.

**Comment by greghoeppner** [comment]
@GitoPhill Would you be able to test the update?  I have done some testing with the Linux paths but I don't have PC-Lint on Linux.  You have to uninstall the version you currently have installed, then install this one from vsix (there is a drop down to install local vsix files). Please let me know if something is not working.
[lintit-0.4.0.zip](https://github.com/greghoeppner/LintIt/files/8258502/lintit-0.4.0.zip)

**Comment by GitoPhill** [comment]
Thank you for your quick reaction on this. I tried your update. With this update, the popup error message does not appear any more. I now see a toast message, saying "Cannot Lint the file ...". 

When using the extension on a Windows Host, I also get this message but I also get some output in the output panel, which helps understanding, why it was not possible.

When using the fixed version in my WSL, I only see the toast message but no output in the output panel. So I have to guess, what might be misconfigured for PC Lint Plus.

Is it somehow possible to forward the output of the Workspace extension within the WSL to the VS Code Client UI on Windows?

**Comment by greghoeppner** [comment]
@GitoPhill if you are not seeing any output, it must be having trouble running at some point.  I think at least you should see something like "linting file ....".  Can you please provide your configuration from the settings.json?   I will try to get another version with more debug output later today.

**Comment by GitoPhill** [comment]
The lintit related part of the configuration looks like this:
`    "lintit.pcLintLocation": "${workspaceFolder}/__tools/pclint/pclp64_linux",
    "lintit.configurations": [
        {
            "includeFolders": ["${workspaceFolder}/shared"],
            "libraryIncludeFolders": ["${workspaceFolder}/shared"],
            "lintFiles": ["${workspaceFolder}/my_custom_lint.lnt", 
                          "${workspaceFolder}/__co-clang.lnt",
                          "${workspaceFolder}/__tools/pc-lint-plus-configurations-master/lnt/au-smori-guidance.lnt",
                          "${workspaceFolder}/__tools/pc-lint-plus-configurations-master/lnt/au-smori-mandatory.lnt",
                          "${workspaceFolder}/__tools/pc-lint-plus-configurations-master/lnt/au-smori-safety.lnt",
                          "${workspaceFolder}/__tools/ds3-pc-lint-plus-configurations-add-ons-master/lnt/ds3-SIL4-exceptions.lnt",
                          "${workspaceFolder}/__tools/pc-lint-plus-configurations-master/lnt/env-xml.lnt",
                          "${workspaceFolder}/lnt/repo_exceptions.lnt",
                          "${workspaceFolder}/__my_project_config.lnt"],
            "sourceFolders": ["${workspaceFolder}/src/corr/corr_interface/corr_load"],
            "extensions": [
                ".c", ".cpp"
            ]
        }
    ]
`
Each time I store, a toast message appears, saying: "Cannot Lint the c file". 

If I invoke the "LintIt: Run" command, a toast message appears, saying: "Cannot Lint the file <First file it finds in the sourceFolders list>". The output panel in my VS Code UI remains clear. There is no output from LintIt at all. That was not the case, when I installed the extension on my Windows host.

**Comment by GitoPhill** [comment]
Thank you for that advice. I now defined the lintit.pcLintLocation variable using an absolute path and I can see some output of PC Lint. So, with your fix, I would consider the issue as resolved.

Just one additional hint/wish: It would be nice to provide a meaningful message, in case the PCLint Plus program cannot be found.

Thanks again and I'm looking forward for the official deployment of the fixed version 👍

**Comment by greghoeppner** [comment]
@GitoPhill, thanks for testing the plugin and identifying the issue.  I have tried to provide a better error message when it is not working.  I released this version and it should be available from the market place.  You will have to uninstall the version that I provided you here first.
